### ISSUE TITLE
Support widely new keyword

### ISSUE THREAD

**Issue by rascaille** [Hyperstore/Jade#10]
Provides mechanisms to support widely new keyword.
new Schema()
new Domain(name:string, schema:Schema)
And especially, allows to use new with a schema element.
Application is a schema element of a loaded schema.
You can type : new Application(); new Applicatoin({Name: "", ...}), new Application(domain:Domain, {Name: ""})

**Comment by malain** [comment]
you can create a new domain element with the new keyword :
var schema = store.getSchema("xxxx);
var elem = new schema.Book(domain)
